name: Run Bot Multi

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Jalankan Bot (Multi)
        run: |
          echo "UTC Time: $(date -u '+%Y-%m-%d %H:%M:%S')"
          echo "WIB Time: $(TZ='Asia/Jakarta' date '+%Y-%m-%d %H:%M:%S')"
          python main_multi.py
        env:
          pw: ${{ secrets.PW }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
